services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Toujou\DatabaseTransfer\:
    resource: '../Classes/*'

  Toujou\DatabaseTransfer\Schema\SchemaMigrator:
    arguments:
      $runtime: '@cache.runtime'
